### ISSUE TITLE
Question: Are there any reasons why or why not to use the factory in non-fixture situations?

### ISSUE THREAD

**Issue by parijke** [zenstruck/foundry#125]
I realy like the foundry approach and I am considering using the factories in my other code as well. But maybe I can't oversee the total impact?

**Comment by kbond** [comment]
You're talking about using in production code? I can't think of "hard" reasons why not - just a few things to be aware of:

- The static madness I use to make autocompletion work is pretty crazy and may have edge cases I'm not aware of - not something I would recommend using in production
- Very little consideration was given to performance. Because I only expected this code to be used in test/dev environments it wasn't a major concern.

**Comment by parijke** [comment]
tx Kevin. I have tested it in my env. and it works like a charm, no perfomance issues as I tested it with a factor 1000 of the reality cases I need. Don't know exactly what you meant by the static madness though...

**Comment by kbond** [comment]
> Don't know exactly what you meant by the static madness though...

Calling `PostFactory::create()` can be called anywhere in your code. The dependencies needed (entity manager, etc) are hidden inside a static configuration object that is injected on application boot. It just isn't a pattern I recommend using.

I did it this way to make autocompletion in your tests work (`PostFactory::create()->someObjectOnYourPostObject()` can be autocompleted by your ide).

**Comment by kbond** [comment]
Closing as answered.
