### ISSUE TITLE
[Question] Run 'clear' after 'flush' call

### ISSUE THREAD

**Issue by TavoNiievez** [zenstruck/foundry#35]
Hi, i have a question, is there no need to clean the object manager after every call to `->flush()`? as I understand in Doctrine the data remains in memory after a call to `->persist()` even after executing a `->flush()` unless explicitly `->clear()` is executed, if i execute a `->createMany(400)` with a lot of data it would not increase that the memory usage incrementally after each persisted object?

https://github.com/zenstruck/foundry/blob/fb5b4ff7e2c224ba6b34069dbc6b459c88f5f806/src/Proxy.php#L100-L101

https://github.com/zenstruck/foundry/blob/fb5b4ff7e2c224ba6b34069dbc6b459c88f5f806/src/Proxy.php#L109-L110

Thanks in advance.

**Comment by kbond** [comment]
Thanks for the report @TavoNiievez. You are correct and I did some tests but didn't see any significant memory savings by adding a `->clear()`. Do you see something different?

Further, calling `->clear()` creates problems with relationships:

```php
PostFactory::new()->create([
    'category' => CategoryFactory::new(),
]);
```

In this example, the Category is persisted and the `em` is flushed and cleared (removing it from memory). When the Post is persisted, the flush gives "A new entity was found through the relationship 'App\Entity\Post#category' that was not configured to cascade persist operations for entity..." exception (because the Category is no longer managed by the `em`). Hope that makes sense...

I would like to eventually have only 1 flush per `->create()`/`->createMany()` - probably for a 2.0 unless I can figure out a way to do without a BC break.

**Comment by TavoNiievez** [comment]
Ok, it's just that I remember that in a legacy application that I managed, the database saved the json data of the users' invoices, at some point we changed this logic:
```php
    public function load(ObjectManager $manager): void {
        for ($i = 0; $i < 800; $i++) {
            $invoice = new Invoice();
            $invoice->setJsonData('C:/..');
			//...
            $manager->persist($invoice);
        }
        $manager->flush();
    }
```
for this other one:
```diff
    public function load(ObjectManager $manager): void {
        for ($i = 0; $i < 800; $i++) {
            $invoice = new Invoice();
            $invoice->setJsonData('C:/..');
			//...
            $manager->persist($invoice);
+        	$manager->flush();
+        	$manager->clear();
        }
-   $manager->flush();
    }
```
and we noticed a difference of 4 seconds... and since the tests had to be executed dozens of times in a day it was an improvement. I was migrating to Foundry in a more updated application under Symfony 5 when I remembered that scenario and decided to ask, but if you performed the tests and did not notice significant differences I guess that solves my doubt.

**Comment by kbond** [comment]
Thanks @TavoNiievez - I'll keep this in mind. If you do see any performance issues yourself, let me know!

**Comment by TavoNiievez** [comment]
I will inform you, thanks to you ;)
