### ISSUE TITLE
Accessing (current) attribute values in a factory?

### ISSUE THREAD

**Issue by mpdude** [zenstruck/foundry#371]
Assume I have a `Transaction` entity with `$begin` and `$end` DateTimes. Both will be given to the constructor, and the constructor will throw an exception if the `$end` time is not after the `begin` time. To make things a bit more interesting, a Transaction may also be "open" which means it has a begin, but no end time yet (so `$end` is nullable).

Now the question:

Can I write my factory in a way that the `begin` is filled in by default, and that I have a "state" method like `closeTransaction(...)` that either sets a given `$end` date or uses Faker to generate one?

```php
final class TransactionFactory extends ModelFactory
{
    protected function getDefaults(): array
    {
        return [
            'begin' => self::faker()->dateTimeBetween('-2 year', '-20 days'),
        ];
    }

    public function closeTransaction(DateTimeInterface $end = null): self
    {
        if (null === $end) {
            $end = self::faker()->dateTimeBetween(/* need to access current `begin` attribute value here */);
        }
        return $this->addState(['end' => $end]);
    }
}
```

Does that make sense?

**Comment by kbond** [comment]
Interesting. You can't access other attributes directly in a state method because they aren't available yet.

I think your best bet is for your state to add a [preIntantiate](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#events-hooks) hook that adds the end time. This closure has the attributes available as the first argument.

**Comment by mpdude** [comment]
So like this?

```php
final class TransactionFactory extends ModelFactory
{
    ...

    public function closeTransaction(DateTimeInterface $end = null): self
    {
        return $this
            ->addState(['end' => $end])
            ->beforeInstantiate(function ($attributes) {
                if (array_key_exists('end', $attributes) && $attributes['end'] === null) {
                    $attributes['end'] = self::faker()->dateTimeBetween($attributes['begin']);
                }
                return $attributes;
            });
    }
}
```

This basically uses the fact that the `end` attribute key is present as a marker that a date needs to be added.

This might work out for the described case. I have, however, another use case in mind (with no good, clear example yet) where it might happen that a later `addState()` leads to a situation where I would prefer to cancel the `beforeInstantiate` closure... This would be easy if that closure itself would be the attribute value, and by overwriting the attribute later on, we'll just forget about the closure.

With the closure being part of the `\Zenstruck\Foundry\Factory::$beforeInstantiate` list, it's difficult to have it removed again.

Is it possible to make the attribute value _itself_ be a callable and resolve it during attribute normalization?

**Comment by kbond** [comment]
Your example above is indeed what I was thinking.

What about _always_ adding the preIntantiate hook (add in initialize) and keeping the state methods as only manipulating `end`?

**Comment by mpdude** [comment]
You're right – the way the hook is written above, I might as well add it in `initialize()`. I'll stress this out a bit and will see if it works for more advanced cases.

Thank you for the time being!

**Comment by janopae** [comment]
Another use case for this would be adding elements to an array. Like `PostFactory::new()->withYellowTag()->withGreenTag()`, but you don't want the yellow tag to be overwritten by the green one.

I solved this case for me by adding an `$addedTags` property (for reading), and also always keeping an artificial `added_tags` attribute in sync with that, so in `beforeInstantiate`, I can merge the content of this artificial attribute with the tags that have been set to the `tags` attribute using `withAttributes`et al. .

But it would be much nicer if factory methods just had access to the state bound to the current factory – essentially providing some sort of access to a merged version of `Factory::attributeSet`.

Maybe, the attribute set could be merged on every modification (instead of keeping a list of attributes from different method calls in memory and only merging them in the end), and we could just have a protected getter for it?

@kbond
