### ISSUE TITLE
\Zenstruck\Foundry\ModelFactory::getDefaults()  is called even if attributes are defined

### ISSUE THREAD

**Issue by syl20b** [zenstruck/foundry#377]
Hi, 

and thank you for this library :)

I'm using it in a Symfony project, with Behat as test runner.

Given the following `ModelFactory` :

```php
final class ServiceFactory extends ModelFactory
{
    /**
     * @return array<string, mixed>
     */
    protected function getDefaults(): array
    {
        return [
            'code' => self::faker()->unique()->word(),
            'label' => self::faker()->text(),
        ];
    }

    protected static function getClass(): string
    {
        return Service::class;
    }
}
```

I'have a couple of Behat Scenario that call that Factory to create new entities : 

```php
ServiceFactory::new(['code' => 'qwerty', 'label' => 'My label'])->create();
```

But I encounter this issue `Maximum retries of 10000 reached without finding a unique value.`  even if I specify all attributes.

As I understand regarding to the source code of the `\Zenstruck\Foundry\ModelFactory::new()` method, the `getDefaults()` method is always called, even if attributes are passed to the method, which leads to call faker and reach the `maximum retries to find a value`.

Do I miss something?
Is there a way to not to call the `getDefaults()` methods when attributes are defined ?

Thank you,

Regards

**Comment by kbond** [comment]
Hey @syl20b,

Calling getDefaults is required to ensure the required attributes are always available if not overridden.

I think maybe your issue is not shutting down foundry after each scenario (calling [`Factory::shutdown()`](https://github.com/zenstruck/foundry/blob/555d547a51506bc0bdd6d287f10048b9aff875fa/src/Factory.php#L252)). This resets the faker unique "cache".

We are planning an official Behat Foundry Context (see #235). In the meantime, take a look at the example context in that issue: https://github.com/zenstruck/foundry/issues/235#issuecomment-1333640916

**Comment by syl20b** [comment]
Thank you for the quick response @kbond 
I will check this out ;)

Do you plan to add this context (#235) in the next release ?

**Comment by kbond** [comment]
Not sure yet, working on a draft PR.
