### ISSUE TITLE
PHPStan issues

### ISSUE THREAD

**Issue by benblub** [zenstruck/foundry#414]
I have two different problems with phpstan and foundry.

**1. load state from a story and using it on typed setter.**

Without the docblock where I specify the var creator is from type User i get stan error `Parameter #1 $creator of method App\Tests\Factory\SessionFactory::creator() expects App\Entity\User, object given.`. Using the docblock is just a workaround and error prone. If we use ->object() from a factory proxy object than its correct unwrapped and we have the correct return type in stan. In both cases Proxy.php Line 114 public function object(): object is called. No clue what's the difference. Another solution would be to replace type User with object in the factory `public function creator(object $creator): self`. But that's also a workaround and less type safe as i wanted^^ 

```php
        /** @var User $creator */
        $creator = WondrousUsersStory::load()::get('rolf')->object();

        $this->addState('restaurant', SessionFactory::new()
            ->creator($creator)
            ->create()
        );
```

In the factory
```php
    public function creator(User $creator): self
    {
        return $this->addState(['creator' => $creator]);
    }
```

**2. The second prob occurs with using pools in combination with createMany**

Stan error: `Parameter #2 $objects of method Zenstruck\Foundry\Story::addToPool() expects object, array<App\Entity\Alternative|Zenstruck\Foundry\Proxy> given.`

Currently I using the stan ignore error as workaround 🤦 
```php
        /** @phpstan-ignore-next-line */
        $this->addToPool('alternatives', AlternativeFactory::createMany(5,
            function () use ($session, &$titles) {
                return [
                    'session' => $session,
                    'title' => array_shift($titles),
                ];
            }
        ));
```

Any ideas how to solve this? I'am also not sure the problem is myCode, foundry or stan related.

**Comment by nikophil** [comment]
Hi @benblub 

**For your first question:** the problem is that stories are not tied to only one type and thus cannot be generic, so `SomeStory::get('something')` returns just a `Proxy` in the type system.

On the other hand, factories are tied to a specific type, and can then be generic: PHPStan knows that `UserFactory::createOne()` returns a `Proxy<User>` thanks to its `@extends ModelFactory<User>` annotation.

The only solution here is to use `WondrousUsersStory::rolf()` (this methods automatically exists thanks [to this](https://github.com/zenstruck/foundry/blob/1.x/src/Story.php#L41)) and to document the method in your story:
```php
/**
 * @method rolf(): Proxy<User>
 */
class WondrousUsersStory extends Story
```
then autocompletion + phpstan will be OK

BTW, @kbond, shouldn't we document this?

NB : yo don't need to use `WondrousUsersStory::load()::get('rolf')`, you can call directly `WondrousUsersStory::get('rolf')` or `WondrousUsersStory::rolf()`


**For the second question:**: have you added the PHPStan specific annotations to the factory? https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#generate It seems PHPStan thinks you `createMany()` returns `Alternative[]|Proxy[]` although it returns `list<Proxy<Alternative>>`.

**Comment by kbond** [comment]
> BTW, @kbond, shouldn't we document this?

https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#story-state contains a little blurb about the magic methods but yes, we could improve this.

**Comment by nikophil** [comment]
see https://github.com/zenstruck/foundry/pull/418

**Comment by benblub** [comment]
Thanks. This helped me.

**Comment by benblub** [comment]
Just for people which are looking here..


### correct syntax
It's need to be
```php
/**
 * @method Proxy<User> rolf()
 */
```

```php
$creator = WondrousUsersStory::load()->rolf()->object();
```

using `@method rolf(): Proxy<User>` will gives a error
```
PHPDoc tag @method has invalid value (rolf(): User): Unexpected token "\n ", expected type at offset  27
```

the errors occurs from the colon `:`.
https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/method.html
`@method [[static] return type] [name]([[type] [parameter]<, ...>]) [<description>]`

### missing parser
For loading fixtures if you get
```
In PhpStanExtractor.php line 67:
                                                                                        
  Attempted to load class "PhpDocParser" from namespace "PHPStan\PhpDocParser\Parser".  
  Did you forget a "use" statement for another namespace?
```

you need to install the doc parser `composer require phpstan/phpdoc-parser`

### other things
btw call WondrousUsersStory::rolf() isn't working for me -> `Static call to instance method App\Story\WondrousOrganisation\WondrousUsersStory::rolf().`

declare the method static in docblock -> `Static call to instance method App\Story\WondrousOrganisation\WondrousUsersStory::rolf().`

This works ` WondrousUsersStory::load()->rolf()`

@nikophil 

### open PR
https://github.com/zenstruck/foundry/pull/420

**Comment by nikophil** [comment]
Hi @benblub 

indeed, the right syntax is the one you say: `@method [[static] return type] [name]([[type] [parameter]<, ...>]) [<description>]`

sorry, for the confusion, I'm always mistaking between documenting `@method` and callables (which is something like `@param rolf(): Proxy<User>`) :shrug:
