### ISSUE TITLE
`FactoryCollection` should create `ArrayCollection` if needed

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#474]
when typing entities collections with `\Doctrine\Common\Collections\Collection` an error occurs:
```php
class Post
{
    /** @var Collection<Comment> */
    private Collection $comments;
}

PostFactory::createOne(
	['comments' => CommentFactory::new()->many(1)]
);
```

The above code results in an error:
```bash
TypeError: Cannot assign array to property App\Domain\Model\Post::$comments of type Doctrine\Common\Collections\Collection
```

although I'm not really sure how we should detect we need collections over arrays :thinking: (try/catch? reflection? use `symfony/property-info`?)

One workaround I'm using also causes problems. 
```php
PostFactory::createOne(
	['comments' => new ArrayCollection(CommentFactory::createMany(1))]
);
```

Above code results in this error:
```
Doctrine\Persistence\Mapping\MappingException: The class 'Zenstruck\Foundry\Proxy' was not found in the chain configured namespaces App\Domain
```

**Comment by oranginalab** [comment]
May be there is a misunderstanding on my side but this seems a serious issue to me as it goes beyond type enforcement. We could relax typing so we can be able to create fixtures  but Foundry factories  returning plain arrays instead of Doctrine Collections will break code relying on Collections features.
Working with Doctrine Collections is the proper way to deal with one-to-many associations and we should not treat them as regular arrays.

So far, the only fix I've been able to figure out is to create the _many_ related objects first and manually add them to a new empty ArrayCollection to, finally, set it to the _one_ object I want to create for my tests.

Something like this:


```php
        // One Deal object can have Many Activities
        
        // We create 5 Activity objects and add them to a new ArrayCollection
        $activities = new ArrayCollection();
        foreach (ActivityFactory::new()->many(5)->create() as $activityProxy) {
            $activities->add($activityProxy->object());
        }
        
        // We create the Deal object and set the newly created ArrayCollection as its activities 
        $deal = DealFactory::new()->create([
            'activities' => $activities
        ]);
``` 

Quite convoluted compared with the succint, nice and expected Foundry syntax:

```php 
        PostFactory::createOne(['comments' => CommentFactory::new()->many(6)]);
```

**Comment by nikophil** [comment]
Yes, thank you to remind me this! I'll give it a try very soon

**Comment by nikophil** [comment]
By the way, if the inverse side of the relation has "adders" (and if your factory does not "force" properties), this should work:
```php
PostFactory::createOne(['comments' => CommentFactory::new()->many(6)]);
```

**Comment by oranginalab** [comment]
> By the way, if the inverse side of the relation has "adders" (and if your factory does not "force" properties), this should work:

`PostFactory::createOne(['comments' => CommentFactory::new()->many(6)]);`

You are absolutely right, @nikophil .
With the proper _adder_ method in the inverse side of the relationship the Collection of related objects is populated as expected.

I really appreciate that you took the time to answer and even propose a fix for version 2.x.

**Comment by nikophil** [comment]
thanks for your kind words :)

I think we'll release the fix in 2.x next week
