### ISSUE TITLE
Calling setters with more than one argument?

### ISSUE THREAD

**Issue by mpdude** [zenstruck/foundry#479]
Is is possible to define attributes in a way that the corresponding method (a setter) is called with more than just one argument?

For example, assume I have an `Order` class that has an `appendLineItem($item, $quantity)` method.

Can I define my `OrderFactory` to include a method like...

```php
class OrderFactory {

  public function addItem($item, $quantity): self
  { 
    return $this->addState(['appendLineItem' => [$item, $quantity]]);
  }
```

The idea is that the attribute value is an array and would be mapped to parameters for the `appendLineItem` method.

**Comment by kbond** [comment]
Would a post-instantiate hook work for this?

**Comment by nikophil** [comment]
I would indeed use a hook for this.

The requested behavior is currently not possible, and I think it could be complex to implement, since we use Symfony's property accessor to hydrate objects.
And presently we don't have any clue to know if the array should be use _as is_ or if it should be destructed and each item in the array would represent a parameter of the target method

**Comment by nikophil** [comment]
I'm closing this since it's a stale issue, and I don't think we will ever support this (beside of using a post instantiate hook)
