### ISSUE TITLE
Codeception support

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#56]
I have never used Codeception so would like help from someone familiar with it to help with possible integration. This is a [naive POC](https://github.com/kbond/foundry-codeception-example) that could be a possible starting point.

Do the PHPUnit assertions available on the `RepositoryProxy` and `Proxy` objects (ie `RepositoryProxy::assertCount()`) work with Codeception?

**Comment by TavoNiievez** [comment]
Hey @kbond, can you please update the description of this issue with the current challenges of integrating with Codeception?

Is there any way we can convert [this](https://github.com/kbond/foundry-codeception-example/blob/master/tests/_support/Helper/Foundry.php) into a module like [module-datafactory](https://github.com/Codeception/module-datafactory/blob/master/src/Codeception/Module/DataFactory.php)

**Comment by kbond** [comment]
Hey @TavoNiievez - I updated the description. Basically, I just need someone who is well acquainted with Codeception to champion the effort to integrate.

**Comment by TavoNiievez** [comment]
Well, I'm not an expert yet, but I know the [symfony module](https://github.com/Codeception/module-symfony) well and worked on its latest versions, the [data-factory module](https://github.com/Codeception/module-datafactory) doesn't seem to have very complex code... So I think I can help with a Foundry module as well.

> (ie convert a real project with many tests to use this module).

We could somehow adapt https://github.com/Codeception/symfony-module-tests so that it can meet that goal.

hopefully, we can make an official module from it.

> I think so but I would like confirmation by someone familiar with the library

not to mention more 😄:
@Naktibalda @DavertMik Do you think we can collaborate to get this module forward? Starting by answering:

> Do the PHPUnit assertions available on the RepositoryProxy and Proxy objects (ie RepositoryProxy::assertCount()) work with Codeception?

**Comment by kbond** [comment]
> hopefully, we can make an official module from it.

Alternatively, I'm open to having the module live in this library.

**Comment by TavoNiievez** [comment]
<details>
<summary>Click to see TavoNiievez's response</summary>
<hr/>

I tried.

I [created a module](https://github.com/TavoNiievez/module-foundry), and I tried the `have` function, which should receive the fqcn of the entity and the attributes.

[Here](https://github.com/TavoNiievez/module-foundry/blob/f6f9b702f74b64b3044a9de05d93e76663dc98a7/src/Codeception/Module/Foundry.php#L132) is the code for the function.

In my `functional.suite.yml` I have:

```yml
actor: FunctionalTester
modules:
    enabled:
        - Foundry:
            depends: Doctrine2
            factories:
                - \App\Factory\UserFactory
        - Symfony:
            app_path: 'src'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
            cleanup: true
```

and in my test I have:

```php
    $I->have(User::class, [
        'email' => 'jane_doe@gmail.com',
        'password' => '123456'
    ]);
    $I->seeNumRecords(1, User::class);
```

everything goes fine until Foundry tries to create the object 🤣 ​​[[line 140](https://github.com/TavoNiievez/module-foundry/blob/f6f9b702f74b64b3044a9de05d93e76663dc98a7/src/Codeception/Module/Foundry.php#L140)]

I am getting the following error:

```
[InvalidArgumentException] Cannot set attribute "0" for object "App\Entity\User" (not public and no setter).
```

However, calling Foundry as I do in my fixtures from there also does not work:

```php
    UserFactory::new([
            'email' => 'jane_doe@gmail.com',
            'password' => '123456'
    ])->create();
```

so I guess the problem is another.

<hr/>
</details>

**Comment by kbond** [comment]
> everything goes fine until Foundry tries to create the object rofl ​​[line 140]
>
> I am getting the following error:

I believe `[$attributes]` should be `$attributes`.

**Comment by TavoNiievez** [comment]
yes, that was it. It works well. I'll continue with the other methods and documentation.

**Comment by TavoNiievez** [comment]
I finished the first draft:

https://github.com/TavoNiievez/module-foundry, also in [Packagist](https://packagist.org/packages/tavoniievez/module-foundry).

**Comment by nikophil** [comment]
stale issue. Don't hesitate to re-open it if you're still planning to work on this
